apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapp  # Match this to your deployment's labels
  ports:
    - port: 8080  # Service port (external)
      targetPort: 8080  # Port your app listens on (internal)

