spring.application.name=Railway Ticket Notification System (RTNS)

# Railway ENVs
railway.api.base-url=https://railspaapi.shohoz.com
railway.api.username=01823923023
railway.api.password=train@123

# Mail ENVs
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=iiucbees@gmail.com
spring.mail.password=tiigbtczvbpwnzaf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false

spring.mail.from=noreply@rtns.com
spring.mail.to=towfiq.106@gmail.com

# App ENVs
ticket.for,future.in.days=10
train.id.ctg.to.dhk=741
train.id.dhk.to.ctg=742


