apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: test  # Match this to your deployment's labels
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000   # Port your app listens on (internal)



